name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.2, 7.3]
        stability: [prefer-lowest, prefer-stable]
    runs-on: ${{ matrix.os }}
    name: PHP${{ matrix.php }} in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer Packages
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: os-${{ matrix.os }}-php${{ matrix.php }}-${{ matrix.stability }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, fileinfo
      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress
      - name: Run tests
        run: vendor/bin/phpunit